services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto

    restart: unless-stopped

    ports:
      # MQTT TCP — сюда подключается Wirepas transport-service
      - "1883:1883"

      # MQTT over WebSocket — сюда подключается Wirepas MQTT Console
      - "9001:9001"

    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

      # Можно оставить для persistence
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

volumes:
  mosquitto-data:
  mosquitto-log:
